//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Game.Properties.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Строка не может быть пустой!.
        /// </summary>
        internal static string Empty_String_Err {
            get {
                return ResourceManager.GetString("Empty_String_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Английский.
        /// </summary>
        internal static string En_Lang {
            get {
                return ResourceManager.GetString("En_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите начальное слово.
        /// </summary>
        internal static string Enter_Start_Word {
            get {
                return ResourceManager.GetString("Enter_Start_Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на введите слово.
        /// </summary>
        internal static string Enter_Word {
            get {
                return ResourceManager.GetString("Enter_Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  в слове.
        /// </summary>
        internal static string In_Word {
            get {
                return ResourceManager.GetString("In_Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Initial_Word {
            get {
                return ResourceManager.GetString("Initial_Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваше слово не может быть длиннее стартового!.
        /// </summary>
        internal static string Long_Player_Word_Err {
            get {
                return ResourceManager.GetString("Long_Player_Word_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слишком много букв.
        /// </summary>
        internal static string Many_Letters_Err {
            get {
                return ResourceManager.GetString("Many_Letters_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти.
        /// </summary>
        internal static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Играть.
        /// </summary>
        internal static string Menu_Game {
            get {
                return ResourceManager.GetString("Menu_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык.
        /// </summary>
        internal static string Menu_Language {
            get {
                return ResourceManager.GetString("Menu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правила.
        /// </summary>
        internal static string Menu_Rules {
            get {
                return ResourceManager.GetString("Menu_Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на МЕНЮ.
        /// </summary>
        internal static string Menu_Title {
            get {
                return ResourceManager.GetString("Menu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В начальном слове нет буквы .
        /// </summary>
        internal static string No_Letter_Err {
            get {
                return ResourceManager.GetString("No_Letter_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игрок.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выиграл игрок номер.
        /// </summary>
        internal static string Player_Win {
            get {
                return ResourceManager.GetString("Player_Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нажмите любую клавишу, чтобы вернуться в меню....
        /// </summary>
        internal static string PressAnyKey {
            get {
                return ResourceManager.GetString("PressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Русский.
        /// </summary>
        internal static string Ru_Lang {
            get {
                return ResourceManager.GetString("Ru_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В начале игры пользователь вводит слово определенной длины.
        ///Суть игры заключается в том, чтобы 2 пользователя поочередно
        ///вводили слова, состоящие из букв первоначально указанного слова.
        ///Проигрывает тот, кто в свою очередь не вводит слово.
        ///
        ///Длина первоначально вводимого слова - от 8 до 30 символов.
        ///На ввод слова дается 20 секунд.
        ///
        ///.
        /// </summary>
        internal static string Rules_Text {
            get {
                return ResourceManager.GetString("Rules_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начальное слово не подходящей длины.
        /// </summary>
        internal static string Start_Word_Error {
            get {
                return ResourceManager.GetString("Start_Word_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время вышло!.
        /// </summary>
        internal static string Time_Over_Err {
            get {
                return ResourceManager.GetString("Time_Over_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Это слово уже было!.
        /// </summary>
        internal static string Word_Been_Err {
            get {
                return ResourceManager.GetString("Word_Been_Err", resourceCulture);
            }
        }
    }
}
